[package]
name = "scale"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"

[dependencies]
rand = {version = "0.7.2", features = ["small_rng"]}
cgmath = {version = "0.17", features = ["mint", "swizzle","serde"]}
specs = {version = "0.15", features = ["shred-derive", "specs-derive", "parallel", "serde"]}
ordered-float = "1.0.2"
ncollide2d = "0.20.1"
nalgebra = "0.18"
imgui = "0.2.1"
serde = "1.0.104"
bincode = "1.2.1"
imgui-inspect = { git = "https://github.com/Uriopass/imgui-inspect-specs/" }
imgui-inspect-derive = { git = "https://github.com/Uriopass/imgui-inspect-specs/" }