[package]
name = "hello_ggez"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"

[dependencies]
rand = {version = "0.7.2", features = ["small_rng"]}
ordered-float = "1.0.2"
engine = { path = "../engine" }