[package]
name = "engine"
version = "0.1.0"
authors = ["Paris Douady <paris.douady@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
cgmath = {version = "0.17", features = ["mint", "swizzle"]}
specs = {version = "0.15", features = ["specs-derive", "parallel"]}
ncollide2d = "0.20"
nalgebra = "0.18"
serde = {version = "1.0"}