---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by paris.
--- DateTime: 11/08/2020 11:05
---

---@class World
world = world

---@class Draw
draw = draw

---@class Vec2
---@class Entity

---@param x number
---@param y number
---@return Vec2
function vec2(x, y) end

---@param self Vec2
---@return number
function Vec2.magnitude(self) end

---@param draw Draw
---@param pos Vec2
---@param radius number
function draw.circle(draw, pos, radius) end

---@param e Entity
---@return Vec2
function world.pos(e) end