data:extend {
    {
        type = "rolling-stock",
        order = "l-1",
        name = "locomotive",
        label = "Locomotive",
        length = 16.75,
        mass = 60,
        max_speed = 200.0,
        acc_force = 2000.0,
        dec_force = 360.0,
        asset = "train.glb",
        price = 100,
    },
    {
        type = "rolling-stock",
        order = "p-1",
        name = "passenger-wagon",
        label = "Passenger Wagon",
        length = 16.75,
        mass = 40,
        max_speed = 200.0,
        acc_force = 0.0,
        dec_force = 240.0,
        asset = "wagon.glb",
        price = 100,
    },
    {
        type = "rolling-stock",
        order = "f-1",
        name = "freight-wagon",
        label = "Freight Wagon",
        length = 16.75,
        mass = 80,
        max_speed = 160.0,
        acc_force = 0.0,
        dec_force = 480.0,
        asset = "wagon_freight.glb",
        price = 100,
    },
    {
        type = "rolling-stock",
        order = "e-1",
        name = "passenger-emu-front",
        label = "Passenger EMU Front",
        length = 28.0,
        mass = 60,
        max_speed = 360.0,
        acc_force = 240.0,
        dec_force = 360.0,
        asset = "passenger-emu-front.glb",
        price = 500,
    },
    {
        type = "rolling-stock",
        order = "e-2",
        name = "passenger-emu-middle",
        label = "Passenger EMU Middle",
        length = 28.0,
        mass = 60,
        max_speed = 360.0,
        acc_force = 240.0,
        dec_force = 360.0,
        asset = "passenger-emu-middle.glb",
        price = 200,
    },
    {
        type = "rolling-stock",
        order = "e-3",
        name = "passenger-emu-rear",
        label = "Passenger EMU Rear",
        length = 28.0,
        mass = 60,
        max_speed = 360.0,
        acc_force = 240.0,
        dec_force = 360.0,
        asset = "passenger-emu-rear.glb",
        price = 500,
    },
}



